#!/bin/bash

INT=$1
echo "Interface: " $INT

echo "Starting Tor process"
sudo networksetup -setsocksfirewallproxystate $INT off
sudo networksetup -setsocksfirewallproxy $INT 127.0.0.1 9050 off
sudo networksetup -setsocksfirewallproxystate $INT on
echo "Proxy SOCKS 127.0.0.1:9050 enabled"

tor