#!/bin/bash

INT=$1
echo "Interface: " $INT

sudo networksetup -setsocksfirewallproxystate $INT off
echo "Disabled proxy SOCKS 127.0.0.1:9050"
PID=$(sudo lsof -i tcp:9050 | grep tor | head -1 | awk '{ print $2 }')

if [[ "$PID" == "" ]]; then
    echo "Tor process is not running, can't drop it"
else
    sudo kill -9 $PID
    echo "Killed tor process"
fi